### PR TITLE
Add bundler

### LINKED ISSUE #7: Use a Bundler for Development?
Are you willing to use a Bundler for development?

One thing that will help with implementing some wanted features, like being able to disable and enable certain color combos, is to maintain a constants file. With that, you can have a single reference to the color combination names that can be used both in the `popup.js` and `content_script.js`.

For the `popup.html`, we can simply use the built in `import/export` module system, but the `content_script.js` file does not have access to this (since it's an injected js file, and not an html file).

If you are willing to use a bundler, which one? Browserify? Webpack? Rollup? Something else?

### PR DESCRIPTION
**Pull request by crookedneighbor**
Closes #7

I like browserify for non-app projects, because there's no additional setup other than installing it and adding the build tasks.

I renamed the `source` directory to `package` to indicate that everything in there is the stuff that will be built for the Chrome extension.

I added a `src` directory where pre-bundled the JavaScript files can be edited.

I have no strong attachment to the directory names, so feel free to update them to whatever.

Happy to make any changes you want!

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Here's a commit to add eslint as well https://github.com/crookedneighbor/mtg-display-color-names/commit/129d3dcd45fdcbc719266df9785e65be37e47870

Wasn't sure if you wanted it all as one PR or incrementally. 

Most of the changes that need to be made was to convert everything to spaces, instead of mixing tabs and spaces.

**Comment by crookedneighbor** [comment]
Is this still something you're interested in doing? If so, I'm happy to make any changes.

If not, also just happy to close the PR.

**Comment by kevinyuliawan** [comment]
@crookedneighbor Sorry about the delay, been busy with other commitments. I definitely want to take a better look and eventually merge this in!

**Comment by crookedneighbor** [comment]
👍 I'll try to check back in about a week. I just don't like leaving PRs open forever.

**Comment by crookedneighbor** [comment]
Gonna close this now, but let me know if you'd like any assistance with this repo.

**Pull request closed without merging**
